### ISSUE TITLE
FR: Show top cpu using processes

### ISSUE THREAD

**Issue by gerroon** [amanusk/s-tui#108]
Hi

It would be nice if the app can also show top couple apps using most of the cpus, say if the cpu usage goes above certain range.

Sure I can fire top or htop but would not be much easier and realtime if this is implemented?

thanks

**Comment by amanusk** [comment]
Hi @gerroon , it should not be too complicated to add the most power hungry process, but there are plenty of programs that do process monitoring already.

The idea is for s-tui to be something similar to the Inter Power gadget for linux, more of a stress-test/benchmarking tool

**Comment by gerroon** [comment]
thanks
