### ISSUE TITLE
Display the status of all CPUs

### ISSUE THREAD

**Issue by Idriss0peaccel** [amanusk/s-tui#109]
Hello,

I would like to know how to display the usage graphs of all cpus ?

**Comment by amanusk** [comment]
Hi, 
By CPU do you mean Cores, or Sockets? 

We are currently working on adding information per core, you can try running the [develp](https://github.com/amanusk/s-tui/tree/develop) brunch, where some of the features are enabled.

**Comment by Idriss0peaccel** [comment]
Hello,
Yes, I wanted to talk about cores.
Thank you for answering.

**Comment by amanusk** [comment]
Please give feedback if you try out the development branch

**Comment by amanusk** [comment]
@Idriss0peaccel Master branch was updated to the new beta version, displaying all CPUs.

Help testing is appreciated
