### ISSUE TITLE
Fan Speed is not Showing

### ISSUE THREAD

**Issue by ShakirKhurshid** [amanusk/s-tui#119]
### Step 1: Ubuntu 16.04

  * System (Intel/AMD/Raspberry Pi etc):intel I5 8300H
  * OS version: 16.04
  * s-tui version: 0.8.3
  * Installation method(pip/PPA/source code): pip
#### Observed Results:

Fan Spped is not displaying

**Comment by amanusk** [comment]
Hi, there can be many reasons to that.
I suggest looking at the discussion in #70
