### ISSUE TITLE
S-tui fails when switching from 0-workers stress to monitor mode.

### ISSUE THREAD

**Issue by nariox** [amanusk/s-tui#120]
### Step 1: Describe your environment
* Archlinux with 5.0.12 kernel
* Thinkpad T480 
* s-tui version 0.8.3
#### Observed Results:
If I set the stress options to 0 worker for all stress options and switch to stress mode, nothing happens (nothing wrong here), but when I switch back to monitor mode, the program crashes.
#### Expected behavior:
The program either realizes that stress needs at least one worker and prevents stress mode being activated without workers or program realizes no workers were called, so it doesn't try to close workers when none are present
#### Traceback output:
[traceback.txt](https://github.com/amanusk/s-tui/files/3149344/traceback.txt)

**Comment by amanusk** [comment]
Thanks @nariox,
I'll push a fix for this in the next version

**Comment by nariox** [comment]
Hi @amanusk,
It's really a low priority bug, it only fails when the user does something that doesn't really make sense, but I thought it'd be right to report it anyway. Thank you for the quick and courteous response.

**Comment by amanusk** [comment]
Fixed in version 1.0, setting workers to 0 does not activate stress at all.
Please validate if you can.

**Comment by nariox** [comment]
Great, no more crashes :)
