### ISSUE TITLE
Memory State

### ISSUE THREAD

**Issue by SirZendom** [amanusk/s-tui#136]
**Is your feature request related to a problem? Please describe.**
Similarly to htop, a graph showing current memory usage.

**Describe the solution you'd like**
Just another stat to be displayed in the main window

**Additional context**
>>htop

**Comment by amanusk** [comment]
Thanks for the interest in the project.
At the moment, there is not intention to show memory usage. htop and similar utilities are doing a great job at that, and s-tui is focused more on CPU performance.

If you wish to implement it yourself, it should not be difficult, and I can explain how to do it
Closing for now
