### ISSUE TITLE
Any chance of monitoring more than a single CPU ?

### ISSUE THREAD

**Issue by Galsplace** [amanusk/s-tui#138]
**Is your feature request related to a problem? Please describe.**
What a great tool !

Tried to run it on an HP server with two CPUs (2 X Intel Skylake)
The program monitors the first CPU only,
Is there a way to get the data for the second CPU as well ?

Thanks a lot !
G.

(HP Server, ProLiant DL380, CentOS7)

**Comment by amanusk** [comment]
Have you tried the beta version?
It supports multiple cores.

**Comment by amanusk** [comment]
New version 1.0 now monitors all cores, on dual CPU systems as well.
