### ISSUE TITLE
power and temp infomation arenot detected

### ISSUE THREAD

**Issue by asherZZZ** [amanusk/s-tui#152]
s-tui version:1.0.0
os kernel:2.6.32-504.16.2.el6.x86_64
cpu:Intel(R) Xeon(R) Gold 5118 CPU @ 2.30G

issue:
I cant saw the power and temp info when launch s-tui，it seems related with POWERCAP and INTEL_RAPL，is there anyone know how to enable them

**Comment by amanusk** [comment]
Are you using a virtual machine by any chance?
Are you getting results when running `sensors` ?

**Comment by amanusk** [comment]
I'll close the issue until more information is provided. Feel free to reopen.
