### ISSUE TITLE
No need to show Stress Timer section if stress is not installed

### ISSUE THREAD

**Issue by singalen** [amanusk/s-tui#157]
I only want to monitor my CPUs, not to stress test it.

"Stress timer" is a waste of space, if stress mode is not installed. "N/A install stress" is too, but probably you want to make users aware of the feature.
![Screen Shot 2020-06-29 at 11 49 23](https://user-images.githubusercontent.com/151199/86044699-514cad00-b9ff-11ea-9c81-1809eb7b9cdd.png)

**Comment by amanusk** [comment]
Right, indeed no reason to display the clock.

**Comment by amanusk** [comment]
Implemented in version 1.0.2. Closing
