### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ovakisan** [amanusk/s-tui#17]
Do you plan to add some kind of logging?

**Comment by amanusk** [comment]
What kind of logging do you mean?
There is dubbug logging when using the --debug flag, and a log of all recorded stats to a csv file when using --csv flag.
Running `s-tui -h` shows these options.

**Comment by ovakisan** [comment]
ahhh yes true, i noticed in source code logging but couldn't figure out how to use it. i needed csv type of logging! thanks :+1: 

maybe put help command in readme for people like me :)
