### ISSUE TITLE
Crash on power read lower than 1W

### ISSUE THREAD

**Issue by amanusk** [amanusk/s-tui#37]
On lower power systems, program crashes if power read is less than 1W

- [x] Max Power read needs to be rounded up
- [x] Side scale needs to show decimal point

**Comment by amanusk** [comment]
@sanderjo 
I have pushed a fix to improve resolution of power read. This will probably not fix the issue of incorrect power read after suspend, but should display a more accurate graph when power is ~1 W

**Comment by sanderjo** [comment]
After a `git pull` ... it looks nice:

![image](https://user-images.githubusercontent.com/1273502/30515590-1ba588b6-9b2b-11e7-8936-2be3494d871c.png)

**Comment by amanusk** [comment]
Great! (BTW, a more accurate readout is available on the side bar if you scroll down).   
Does the problem persist after suspend?

**Comment by sanderjo** [comment]
> Does the problem persist after suspend?

Yes: after a suspend and wake-up:

![image](https://user-images.githubusercontent.com/1273502/30515705-37cf56be-9b2d-11e7-85e4-294e3d5ff272.png)

![image](https://user-images.githubusercontent.com/1273502/30515718-5fb47aec-9b2d-11e7-9921-5f1a9857d9eb.png)

**Comment by sanderjo** [comment]
What is the meaning of he file `/sys/class/powercap/intel-rapl/intel-rapl\:0/intel-rapl\:0\:0/energy_uj`, so with the extra `intel-rapl\:0\:0` in it ?
It seems to show more normal values (if I divide by 1000, not 1 million), also after a suspend. 

```
$ ./sj2.sh 
Linux Stream-13 4.13.0-041300-generic #201709031731 SMP Sun Sep 3 21:33:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
388804960
388804
388815648
10
388821376
5
388829728
8
388834944
5
388843808
8
388849248
5
388853856
4
388861312
7
388866336
5
388870624
4
```

**Comment by amanusk** [comment]
intel-rapl\:0\:0 should be 'Cores' value and intel-rapl\:0\:1 is 'Uncore'  
intel-rapl\:0 should sum these together.

**Comment by amanusk** [comment]
I'll close the issue, as there is no longer a crash.  
I'll open a new one to track irregular values after suspend.
