### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by ilhamdoanggg** [amanusk/s-tui#45]
```
Traceback (most recent call last):
  File "/usr/bin/s-tui", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by amanusk** [comment]
There is probably a problem with your pip installation.  
Please try one of the solutions here:
[No module named pkg_resources](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources)

**Comment by ilhamdoanggg** [comment]
thanks a lot
