### ISSUE TITLE
No temperature and monitor values are available

### ISSUE THREAD

**Issue by josanabr** [amanusk/s-tui#63]
### Step 1: Describe your environment

  * System (Intel/AMD/Raspberry Pi etc): __Intel___
  * OS version: __macOS High Sierra 10.13.4___
  * s-tui version: _0.7.6____
  * Installation method(pip/PPA/source code): __pip___
  
### Step 2: Describe the problem:
I wonder if an extra code is needed to bring full support to Mac OSX systems. My processor is i5-5257U @ 2.70GHz?

**Comment by amanusk** [comment]
Yes, not all features are currently supported on macOS, as metioned in #49 and #27. Hopefully, I will be able to work on this soon if I get access to hardware. I'll close this for now, and will update in the alredy opened issues.
