### ISSUE TITLE
s-tui crashes and is stuck after changing temprature sensor

### ISSUE THREAD

**Issue by giltsuker** [amanusk/s-tui#79]
### Step 1: Describe your environment

  * System (Intel/AMD/Raspberry Pi etc): ubuntu
  * OS version: 16.04
  * s-tui version: 0.8.0
  * Installation method(pip/PPA/source code): source code
  
#### Observed Results:

s-tui stuck, and cannot terminate program. even with ctrl+C
  
#### Debug Results, output of `s-tui -d` created in a file `_s-tui.log`: 

exceptions log:
[err.txt](https://github.com/amanusk/s-tui/files/2315935/err.txt)

stui log:
[_s-tui.log](https://github.com/amanusk/s-tui/files/2315936/_s-tui.log)
  
#### Steps to reproduce:
1. start stui from source
 python3 -m s_tui.s_tui
2. start stress
3. return to "monitor" mode
4. change temprature sensor
5. press "monitor" mode
s-tui now crashes, and immediately restart with every button press, even "Quit" and "ctrl-C"

**Comment by amanusk** [comment]
Should be fixed in #80. 

If you want to give it a try.
