### ISSUE TITLE
No valid Python3 package

### ISSUE THREAD

**Issue by mkesper** [amanusk/s-tui#90]
### Step 1: Describe your environment

  * System (Intel/AMD/Raspberry Pi etc): Intel
  * OS version: Debian Buster
  * s-tui version: 0.8.2
  * Installation method(pip/PPA/source code): Git clone
  
#### Observed Results:

  * What happened? (Traceback of a crash/Image/description):
  
If called as a module with Python2, the program will start, but Python3 does not find it as a module:

```
mkesper@debian:~/src/mkesper/s-tui $ python2 --version
Python 2.7.15+
mkesper@debian:~/src/mkesper/s-tui $ python3 --version
Python 3.6.6
mkesper@debian:~/src/mkesper/s-tui $ python2 -m s_tui/s_tui --version
s-tui 0.8.2 - (C) 2017-2018 Alex Manuskin, Gil Tsuker
    Released under GNU GPLv2
mkesper@debian:~/src/mkesper/s-tui $ python3 -m s_tui/s_tui --version
/usr/bin/python3: No module named s_tui/s_tui
mkesper@debian:~/src/mkesper/s-tui $ python3 -m s_tui/s_tui.py --version
/usr/bin/python3: Error while finding module specification for 's_tui/s_tui.py' (ModuleNotFoundError: No module named 's_tui/s_tui')

```
  
#### Steps to reproduce:
1. Git clone the source
2. Enter the source directory
3. Execute

```
python3 -m s_tui/s_tui --version
```

**Comment by amanusk** [comment]
To my knowledge, the way to run modules with `-m` is by separating them with `.` instead of `
/`
Both `python3 -m s_tui.s_tui --version` and `python2 -m s_tui.s_tui --version` should work. 
Or is there a case where `s_tui/s_tui` is needed?

**Comment by mkesper** [comment]
You're right. My bad, python2 seems to be more lenient here.
